### ISSUE TITLE
function name suggestions

### ISSUE THREAD

**Issue by nsheff** [databio/MIRA#10]
I have 2 issues with the function name `SumExpToMIRA`

1. "SumExp" is really ambiguous, since Sum and Exp both can main many things. I suggest changing it to SummarizedExperiment.

2. "ToMIRA" implies that MIRA is a data structure, but it is not.

I suggest: `SummarizedExperimentToDataTable` or `SummarizedExperimentToBSDT` instead.

**Comment by j-lawson** [comment]
Agreed. I changed it to SummarizedExperimentToDataTable. I also changed bsseqToMIRA to bsseqToDataTable.
