### ISSUE TITLE
cryptic error message; change sampleName handling

### ISSUE THREAD

**Issue by nsheff** [databio/MIRA#13]
I got this error message

```
Converting to GRangesList...
Error in MIRA::aggregateMethyl(rrbsDat, neuDMRgr) : 
  BSDT should have sampleName col if sampleNameInBSDT = TRUE
```
I did not set sampleNameInBSDT. Therefore, I do not know how to respond. Can you please clarify the error so an uninitiated user will understand it?

I think I see what's happening.

sampleNameInBSDT should just be an arg for `sampleName`. if set to NULL or FALSE it should not use it, and otherwise it should be the name of the col; not require me to create a new col with a specific name. I also think it should default to off; right now it basically defaults to "sampleName"

**Comment by nsheff** [comment]
yeah, I had my sample names in a column called  `id`. 
So this fixed it:
`setnames(agedMiceRrbs, c("id"), c("sampleName"))`

but it would be better if I could fix it with:

`aggregateMethyl(..., idCol="id")`

**Comment by nsheff** [comment]
`plotMIRAProfiles` could work the same way
Along these lines, I got:
```
> MIRA::plotMIRAProfiles(do.call(rbind, agMethList))
Warning message:
In MIRA::plotMIRAProfiles(do.call(rbind, agMethList)) :
  sampleType column must exist if it is desired to split up sample types by color
```

As a general rule, it's better to not require a specific column name, but let the user specify it with a parameter. Here I want to use `sampleName` to color. I'd rather not have to change my data, but to pass a param.

**Comment by j-lawson** [comment]
I think I took out that warning at some point and changed how the function
dealt with sampleName column. We probably need to update the version of
MIRA on Rivanna.

**Comment by nsheff** [comment]
Yep, probably right!

**Comment by nsheff** [comment]
I updated it. will let you know how it goes.

**Comment by j-lawson** [comment]
Updating the version resolved the problem so I'm closing the issue.
