### ISSUE TITLE
list numbers reverted

### ISSUE THREAD

**Issue by nsheff** [databio/MIRA#16]
Herve suggested changing the numbers of list to not start a 0 in [his review](https://github.com/Bioconductor/Contributions/issues/355): 

> The section numbers in the 2 vignettes all start with "0." (e.g. 0.1, 0.2, etc...). Please use more conventional numbers (e.g. 1, 2, etc...).

We supposedly fixed this:

> We fixed the section numbers in the vignettes.

But when I look at the vignettes the numbers are back to 0.1, and 0.2. Did this get reverted somehow?

**Comment by nsheff** [comment]
I trace it to [this commit](https://github.com/databio/MIRA/commit/4eb4d791b52aa8786926b7d3973ff60eb054608b) and it doesn't look like it's ever been updated since then.

**Comment by j-lawson** [comment]
I changed the problem of list numbers starting with 0 a while ago, I think by changing the level of Markdown header (hash signs) which updated the numbers. I can make the list not start at 0 though.
