### ISSUE TITLE
build tools

### ISSUE THREAD

**Issue by vpnagraj** [databio/MIRA#4]
@j-lawson this isn't so much an issue as a recommendation / potential enhancement ... 

@nsheff and i discussed the workflow for preparing MIRA for release ... in the past i've used two tools that you might find helpful:

- `devtools:build_win()` will bundle your package, build it on a Windows server and email you the the results with WARNINGs, ERRORs, NOTEs and other diagnostics <https://rdrr.io/cran/devtools/man/build_win.html>
- Travis CI integration will build your package in Ubuntu after each commit ... i have this set up on the [dev branch of simpleCache](https://github.com/databio/simpleCache/tree/dev) and would be happy to help do the same for MIRA when you're ready to make it a public repo <https://travis-ci.org/>

**Comment by j-lawson** [comment]
The suggestions were implemented. Thanks!
